<?php

namespace Moonspot\Phlag\Mapper;

/**
 * PhlagSession Mapper
 *
 * Maps PhlagSession value objects to the phlag_sessions database table.
 * Used by DatabaseSessionHandler to store and retrieve session data
 * across multiple application instances.
 *
 * ## Key Features
 *
 * - Non-auto-increment primary key (session_id is generated by PHP)
 * - Handles text session data (serialized by PHP's session handler)
 * - Supports efficient garbage collection via last_activity index
 *
 * ## Usage
 *
 * This mapper is primarily used internally by DatabaseSessionHandler.
 * Direct usage is rare but follows standard DataMapper patterns:
 *
 * ```php
 * $mapper = new PhlagSession();
 * $session = $mapper->get(session_id());
 * ```
 *
 * @package Moonspot\Phlag\Mapper
 */
class PhlagSession extends \DealNews\DB\AbstractMapper {

    /**
     * Database name
     */
    public const DATABASE_NAME = 'phlag';

    /**
     * Table name
     */
    public const TABLE = 'phlag_sessions';

    /**
     * Table primary key column name
     *
     * Heads-up: session_id is NOT auto-increment. PHP generates
     * the session ID, and we use it as the primary key.
     */
    public const PRIMARY_KEY = 'session_id';

    /**
     * Name of the class the mapper is mapping
     */
    public const MAPPED_CLASS = \Moonspot\Phlag\Data\PhlagSession::class;

    /**
     * Defines the properties that are mapped and any
     * additional information needed to map them.
     */
    public const MAPPING = [
        'session_id'      => [],
        'session_data'    => [],
        'last_activity'   => [],
        'create_datetime' => [
            'read_only' => true,
        ],
    ];

    /**
     * Saves a PhlagSession object to the database
     *
     * Overrides the parent save method to handle non-auto-increment
     * primary keys properly. Since session_id is provided by PHP's
     * session management and not auto-generated by the database,
     * we skip the lastInsertId() call that would fail on PostgreSQL.
     *
     * ## How It Works
     *
     * - Performs the same save logic as parent
     * - Skips lastInsertId() call since we provide the ID manually
     * - Properly handles both INSERT and UPDATE operations
     *
     * ## PostgreSQL Compatibility
     *
     * PostgreSQL throws "lastval is not yet defined in this session"
     * when lastInsertId() is called without a sequence. Since we provide
     * the session_id manually, we don't need to fetch it from the database.
     *
     * ## Usage
     *
     * ```php
     * $session = new PhlagSession();
     * $session->session_id = session_id();
     * $session->session_data = serialize($_SESSION);
     * $session->last_activity = time();
     * 
     * $mapper = new PhlagSession();
     * $saved = $mapper->save($session);
     * ```
     *
     * @param object $object PhlagSession object to save
     *
     * @return object Saved PhlagSession object
     *
     * @throws \RuntimeException If session_id is empty
     * @throws \PDOException If database operation fails
     */
    public function save($object): object {

        // Validate session_id is set
        if (empty($object->session_id)) {
            throw new \RuntimeException(
                'Cannot save PhlagSession: session_id must be set before saving'
            );
        }

        $already_in_transaction = $this->crud->pdo->inTransaction();

        if (!$already_in_transaction) {
            $this->crud->pdo->beginTransaction();
        }

        try {
            $update_constraint = $this->getUpdateConstraint($object);
            $data              = $this->getData($object);

            $insert = false;

            // Check if session exists in database
            $existing = $this->crud->read(
                $this->table,
                [self::PRIMARY_KEY => $object->session_id]
            );

            if (empty($existing)) {
                $insert = true;
            }

            if ($insert) {
                // Insert with our provided session_id
                $success = $this->crud->create($this->table, $data);
                // Don't call lastInsertId() - we already have the ID
            } else {
                // Update existing session
                $success = $this->crud->update(
                    $this->table,
                    $data,
                    $update_constraint
                );
            }

            if ($success) {
                $object = $this->saveRelations($object);
                // Don't reload - we already have all the data
                // (only create_datetime is DB-generated, which isn't needed)
            }

            if (!$already_in_transaction) {
                $this->crud->pdo->commit();
            }

        } catch (\PDOException $e) {
            if (!$already_in_transaction) {
                $this->crud->pdo->rollBack();
            }
            throw $e;
        }

        return $object;
    }
}
