<?php

namespace Moonspot\Phlag\Data;

/**
 * Phlag Session Value Object
 *
 * Represents a user session stored in the database. This enables
 * session sharing across multiple application instances for
 * horizontal scaling and high availability.
 *
 * ## Properties
 *
 * - **session_id**: PHP-generated session identifier (128 chars max)
 * - **session_data**: Serialized session data (blob)
 * - **last_activity**: Unix timestamp of last session activity
 * - **create_datetime**: ISO 8601 timestamp of session creation
 *
 * ## Usage
 *
 * ```php
 * $session = new PhlagSession();
 * $session->session_id = session_id();
 * $session->session_data = serialize($_SESSION);
 * $session->last_activity = time();
 * ```
 *
 * Heads-up: This object is primarily used by DatabaseSessionHandler.
 * Direct instantiation is rarely needed in application code.
 *
 * @package Moonspot\Phlag\Data
 */
class PhlagSession {

    /**
     * Session identifier
     *
     * Generated by PHP's session management system. Maximum length
     * is 128 characters to accommodate future session ID formats.
     *
     * @var string
     */
    public string $session_id = '';

    /**
     * Serialized session data
     *
     * Contains the raw serialized session data stored in $_SESSION.
     * PHP's session handler automatically serializes and unserializes
     * this data using the configured session serializer.
     *
     * @var string
     */
    public string $session_data = '';

    /**
     * Last activity timestamp
     *
     * Unix timestamp indicating when the session was last accessed.
     * Used for timeout detection and garbage collection.
     *
     * @var int
     */
    public int $last_activity = 0;

    /**
     * Creation datetime
     *
     * ISO 8601 formatted timestamp of when the session was created.
     * Populated automatically by the database on insert.
     *
     * @var string
     */
    public string $create_datetime = '';
}
